version: '3.2'
networks:
  default: ~
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "8989:80"
    networks:
      default: ~
  php:
    build:
      args:
        user: matt
        uid: 1000
      context: .
      dockerfile: ./docker/php/Dockerfile
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    command: php-fpm
    ports:
      - 9000
    networks:
      default: ~
